/* ═══════════════════════════════════════════════════════════════
   لائحة تنظيم العمل — مكتب هاني محمد عسيري للاستشارات الهندسية
   رقم الاعتماد: 978004 | تاريخ الاعتماد: 1445/5/29 هـ
   جداول المخالفات والجزاءات — الفصل الأول، الثاني، الثالث
   المصدر: اللائحة التنظيمية المعتمدة من وزارة الموارد البشرية
   ═══════════════════════════════════════════════════════════════ */

export const LAIHA_INFO = {
  approvalNumber: "978004",
  approvalDate: "1445-05-29 هـ",
  source: "وزارة الموارد البشرية والتنمية الاجتماعية",
  company: "مكتب هاني محمد عسيري للاستشارات الهندسية",
  companyNumber: "2030908-9",
  baseLaw: "المرسوم الملكي رقم (م/51) وتاريخ 23/08/1426هـ وتعديلاته",
};

/* الجزاءات المرجعية من المادة (41) */
export const PENALTY_TYPES = {
  WARNING: { code: "WARNING", label: "إنذار كتابي", description: "كتاب يوضح المخالفة مع التنبيه لجزاء أشد عند التكرار" },
  FINE_5: { code: "FINE_5", label: "خصم 5%", description: "خصم 5% من الأجر اليومي" },
  FINE_10: { code: "FINE_10", label: "خصم 10%", description: "خصم 10% من الأجر اليومي" },
  FINE_15: { code: "FINE_15", label: "خصم 15%", description: "خصم 15% من الأجر اليومي" },
  FINE_20: { code: "FINE_20", label: "خصم 20%", description: "خصم 20% من الأجر اليومي" },
  FINE_25: { code: "FINE_25", label: "خصم 25%", description: "خصم 25% من الأجر اليومي" },
  FINE_30: { code: "FINE_30", label: "خصم 30%", description: "خصم 30% من الأجر اليومي" },
  FINE_50: { code: "FINE_50", label: "خصم 50%", description: "خصم 50% من الأجر اليومي" },
  FINE_75: { code: "FINE_75", label: "خصم 75%", description: "خصم 75% من الأجر اليومي" },
  FINE_1DAY: { code: "FINE_1DAY", label: "خصم يوم", description: "خصم أجر يوم كامل" },
  FINE_2DAYS: { code: "FINE_2DAYS", label: "خصم يومين", description: "خصم أجر يومين" },
  FINE_3DAYS: { code: "FINE_3DAYS", label: "خصم 3 أيام", description: "خصم أجر 3 أيام" },
  FINE_4DAYS: { code: "FINE_4DAYS", label: "خصم 4 أيام", description: "خصم أجر 4 أيام" },
  FINE_5DAYS: { code: "FINE_5DAYS", label: "خصم 5 أيام", description: "خصم أجر 5 أيام" },
  SUSPENSION: { code: "SUSPENSION", label: "إيقاف عن العمل", description: "منع من مزاولة العمل مع الحرمان من الأجر" },
  DENY_PROMOTION: { code: "DENY_PROMOTION", label: "حرمان من الترقية/العلاوة", description: "الحرمان من الترقية أو العلاوة لمرة واحدة" },
  TERMINATION_WITH: { code: "TERMINATION_WITH", label: "فصل مع المكافأة", description: "فصل مع الاحتفاظ بمكافأة نهاية الخدمة" },
  TERMINATION_WITHOUT: { code: "TERMINATION_WITHOUT", label: "فصل دون مكافأة (م.80)", description: "فسخ العقد دون مكافأة أو إشعار أو تعويض وفق المادة 80" },
  WARNING_BEFORE_TERMINATION: { code: "WARNING_BEFORE_TERMINATION", label: "إنذار بالفصل طبقاً للمادة 80", description: "إنذار كتابي قبل الفصل النهائي" },
};

/* ═══ الفصل الأول: مخالفات تتعلق بمواعيد العمل (16 بند) ═══ */
export const VIOLATIONS_WORKING_HOURS = [
  {
    id: "WH-01",
    chapter: "مواعيد العمل",
    number: 1,
    description: "التأخر عن مواعيد الحضور للعمل لغاية (15) دقيقة دون إذن أو عذر مقبول: إذا لم يترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "WARNING", second: "FINE_5", third: "FINE_10", fourth: "FINE_20" },
    autoDetectable: true,
    detectionRule: { type: "late", maxMinutes: 15, disruption: false },
    enabled: true,
    autoApply: true, // إذا false → يمر على HR
  },
  {
    id: "WH-02",
    chapter: "مواعيد العمل",
    number: 2,
    description: "التأخر عن مواعيد الحضور للعمل لغاية (15) دقيقة دون إذن أو عذر مقبول: إذا ترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "WARNING", second: "FINE_15", third: "FINE_25", fourth: "FINE_50" },
    autoDetectable: false, // التعطيل يحتاج تأكيد يدوي
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-03",
    chapter: "مواعيد العمل",
    number: 3,
    description: "التأخر عن مواعيد الحضور للعمل أكثر من (15) دقيقة لغاية (30) دقيقة دون إذن أو عذر مقبول: إذا لم يترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "FINE_10", second: "FINE_15", third: "FINE_25", fourth: "FINE_50" },
    autoDetectable: true,
    detectionRule: { type: "late", minMinutes: 16, maxMinutes: 30, disruption: false },
    enabled: true,
    autoApply: true,
  },
  {
    id: "WH-04",
    chapter: "مواعيد العمل",
    number: 4,
    description: "التأخر عن مواعيد الحضور للعمل أكثر من (15) دقيقة لغاية (30) دقيقة دون إذن أو عذر مقبول: إذا ترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "FINE_25", second: "FINE_50", third: "FINE_75", fourth: "FINE_1DAY" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-05",
    chapter: "مواعيد العمل",
    number: 5,
    description: "التأخر عن مواعيد الحضور للعمل أكثر من (30) دقيقة لغاية (60) دقيقة دون إذن أو عذر مقبول: إذا لم يترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "FINE_25", second: "FINE_50", third: "FINE_75", fourth: "FINE_1DAY" },
    autoDetectable: true,
    detectionRule: { type: "late", minMinutes: 31, maxMinutes: 60, disruption: false },
    enabled: true,
    autoApply: true,
  },
  {
    id: "WH-06",
    chapter: "مواعيد العمل",
    number: 6,
    description: "التأخر عن مواعيد الحضور للعمل أكثر من (30) دقيقة لغاية (60) دقيقة دون إذن أو عذر مقبول: إذا ترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "FINE_30", second: "FINE_50", third: "FINE_1DAY", fourth: "FINE_2DAYS" },
    notes: "بالإضافة إلى حسم أجر دقائق التأخر",
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-07",
    chapter: "مواعيد العمل",
    number: 7,
    description: "التأخر عن مواعيد الحضور للعمل لمدة تزيد على ساعة دون إذن أو عذر مقبول: سواءً ترتب أو لم يترتب على ذلك تعطيل عمال آخرين",
    penalties: { first: "WARNING", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_3DAYS" },
    notes: "بالإضافة إلى حسم أجر ساعات التأخر",
    autoDetectable: true,
    detectionRule: { type: "late", minMinutes: 61 },
    enabled: true,
    autoApply: true,
  },
  {
    id: "WH-08",
    chapter: "مواعيد العمل",
    number: 8,
    description: "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما لا يتجاوز (15) دقيقة",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_25", fourth: "FINE_1DAY" },
    notes: "بالإضافة إلى حسم أجر مدة ترك العمل",
    autoDetectable: true,
    detectionRule: { type: "early_leave", maxMinutes: 15 },
    enabled: true,
    autoApply: true,
  },
  {
    id: "WH-09",
    chapter: "مواعيد العمل",
    number: 9,
    description: "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما يتجاوز (15) دقيقة",
    penalties: { first: "FINE_10", second: "FINE_25", third: "FINE_50", fourth: "FINE_1DAY" },
    notes: "بالإضافة إلى حسم أجر مدة ترك العمل",
    autoDetectable: true,
    detectionRule: { type: "early_leave", minMinutes: 16 },
    enabled: true,
    autoApply: true,
  },
  {
    id: "WH-10",
    chapter: "مواعيد العمل",
    number: 10,
    description: "البقاء في أماكن العمل أو العودة إليها بعد انتهاء مواعيد العمل دون إذن مسبق",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_25", fourth: "FINE_1DAY" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-11",
    chapter: "مواعيد العمل",
    number: 11,
    description: "الغياب دون إذن كتابي أو عذر مقبول لمدة يوم، خلال السنة العقدية الواحدة",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_4DAYS", fourth: "DENY_PROMOTION" },
    autoDetectable: true,
    detectionRule: { type: "absent", days: 1 },
    enabled: true,
    autoApply: false, // الغياب حساس — يمر على HR
  },
  {
    id: "WH-12",
    chapter: "مواعيد العمل",
    number: 12,
    description: "الغياب المتصل دون إذن كتابي أو عذر مقبول من يومين إلى ستة أيام، خلال السنة العقدية الواحدة",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_4DAYS", fourth: "DENY_PROMOTION" },
    notes: "بالإضافة إلى حسم أجر مدة الغياب",
    autoDetectable: true,
    detectionRule: { type: "absent_consecutive", minDays: 2, maxDays: 6 },
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-13",
    chapter: "مواعيد العمل",
    number: 13,
    description: "الغياب المتصل دون إذن كتابي أو عذر مقبول من سبعة أيام إلى عشرة أيام، خلال السنة العقدية الواحدة",
    penalties: { first: "FINE_4DAYS", second: "FINE_5DAYS", third: "DENY_PROMOTION", fourth: "TERMINATION_WITH" },
    notes: "بالإضافة إلى حسم أجر مدة الغياب",
    autoDetectable: true,
    detectionRule: { type: "absent_consecutive", minDays: 7, maxDays: 10 },
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-14",
    chapter: "مواعيد العمل",
    number: 14,
    description: "الغياب المتصل دون إذن كتابي أو عذر مقبول من أحد عشر يوماً إلى أربعة عشر يوماً، خلال السنة العقدية الواحدة",
    penalties: { first: "FINE_5DAYS", second: "WARNING_BEFORE_TERMINATION", third: "TERMINATION_WITHOUT", fourth: null },
    notes: "بالإضافة إلى حسم أجر مدة الغياب",
    autoDetectable: true,
    detectionRule: { type: "absent_consecutive", minDays: 11, maxDays: 14 },
    enabled: true,
    autoApply: false,
  },
  {
    id: "WH-15",
    chapter: "مواعيد العمل",
    number: 15,
    description: "الانقطاع عن العمل دون سبب مشروع مدة تزيد على خمسة عشر يوماً متصلة، خلال السنة العقدية الواحدة",
    penalties: { first: "TERMINATION_WITHOUT", second: null, third: null, fourth: null },
    notes: "الفصل دون مكافأة أو تعويض، على أن يسبقه إنذار كتابي بعد الغياب مدة عشرة أيام، في نطاق حكم المادة (80) من نظام العمل",
    autoDetectable: true,
    detectionRule: { type: "absent_consecutive", minDays: 15 },
    enabled: true,
    autoApply: false, // فصل لازم يمر على HR + مدير عام
  },
  {
    id: "WH-16",
    chapter: "مواعيد العمل",
    number: 16,
    description: "الغياب المتقطع دون سبب مشروع مدداً تزيد في مجموعها على ثلاثين يوماً خلال السنة العقدية الواحدة",
    penalties: { first: "TERMINATION_WITHOUT", second: null, third: null, fourth: null },
    notes: "الفصل دون مكافأة أو تعويض، على أن يسبقه إنذار كتابي بعد الغياب مدة عشرين يوماً، في نطاق حكم المادة (80) من نظام العمل",
    autoDetectable: true,
    detectionRule: { type: "absent_scattered", minDaysInYear: 30 },
    enabled: true,
    autoApply: false,
  },
];

/* ═══ الفصل الثاني: مخالفات تتعلق بتنظيم العمل (18 بند) ═══ */
export const VIOLATIONS_WORK_ORGANIZATION = [
  {
    id: "WO-01",
    chapter: "تنظيم العمل",
    number: 1,
    description: "التواجد دون مبرر في غير مكان العمل المخصص للعامل أثناء وقت الدوام",
    penalties: { first: "FINE_10", second: "FINE_25", third: "FINE_50", fourth: "FINE_1DAY" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-02",
    chapter: "تنظيم العمل",
    number: 2,
    description: "استقبال زائرين في غير أمور عمل المنشأة في أماكن العمل، دون إذن من الإدارة",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_15", fourth: "FINE_25" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-03",
    chapter: "تنظيم العمل",
    number: 3,
    description: "استعمال آلات ومعدات وأدوات المنشأة لأغراض خاصة، دون إذن",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_25", fourth: "FINE_50" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-04",
    chapter: "تنظيم العمل",
    number: 4,
    description: "تدخل العامل دون وجه حق في أي عمل ليس في اختصاصه أو لم يعهد به إليه",
    penalties: { first: "FINE_50", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_3DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-05",
    chapter: "تنظيم العمل",
    number: 5,
    description: "الخروج أو الدخول من غير المكان المخصص لذلك",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_15", fourth: "FINE_25" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-06",
    chapter: "تنظيم العمل",
    number: 6,
    description: "الإهمال في تنظيف الآلات وصيانتها، أو عدم العناية بها، أو عدم التبليغ عن ما بها من خلل",
    penalties: { first: "FINE_50", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_3DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-07",
    chapter: "تنظيم العمل",
    number: 7,
    description: "عدم وضع أدوات الإصلاح والصيانة واللوازم الأخرى في الأماكن المخصصة لها، بعد الانتهاء من العمل",
    penalties: { first: "WARNING", second: "FINE_25", third: "FINE_50", fourth: "FINE_1DAY" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-08",
    chapter: "تنظيم العمل",
    number: 8,
    description: "تمزيق أو إتلاف إعلانات أو بلاغات إدارة المنشأة",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-09",
    chapter: "تنظيم العمل",
    number: 9,
    description: "الإهمال في العهد التي بحوزته (سيارات، آلات، أجهزة، معدات، أدوات، إلخ)",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-10",
    chapter: "تنظيم العمل",
    number: 10,
    description: "الأكل في مكان العمل، أو غير المكان المعد له، أو في غير أوقات الراحة",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_15", fourth: "FINE_25" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-11",
    chapter: "تنظيم العمل",
    number: 11,
    description: "النوم أثناء العمل",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_25", fourth: "FINE_50" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-12",
    chapter: "تنظيم العمل",
    number: 12,
    description: "النوم في الحالات التي تستدعي يقظة مستمرة",
    penalties: { first: "FINE_50", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_3DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-13",
    chapter: "تنظيم العمل",
    number: 13,
    description: "التسكع، أو وجود العامل في غير مكان عمله، أثناء ساعات العمل",
    penalties: { first: "FINE_10", second: "FINE_25", third: "FINE_50", fourth: "FINE_1DAY" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-14",
    chapter: "تنظيم العمل",
    number: 14,
    description: "التلاعب في إثبات الحضور والانصراف",
    penalties: { first: "FINE_1DAY", second: "FINE_2DAYS", third: "DENY_PROMOTION", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-15",
    chapter: "تنظيم العمل",
    number: 15,
    description: "عدم إطاعة الأوامر العادية الخاصة بالعمل، أو عدم تنفيذ التعليمات الخاصة بالعمل، والمعلقة في مكان ظاهر",
    penalties: { first: "FINE_25", second: "FINE_50", third: "FINE_1DAY", fourth: "FINE_2DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-16",
    chapter: "تنظيم العمل",
    number: 16,
    description: "التحريض على مخالفة الأوامر والتعليمات الخطية الخاصة بالعمل",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-17",
    chapter: "تنظيم العمل",
    number: 17,
    description: "التدخين في الأماكن المحظورة، والمعلن عنها للمحافظة على سلامة العمال والمنشأة",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "WO-18",
    chapter: "تنظيم العمل",
    number: 18,
    description: "الإهمال أو التهاون في العمل الذي قد ينشأ عنه ضرر في صحة العمال أو سلامتهم، أو في المواد أو الأدوات والأجهزة",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
];

/* ═══ الفصل الثالث: مخالفات تتعلق بسلوك العامل (16 بند) ═══ */
export const VIOLATIONS_BEHAVIOR = [
  {
    id: "BH-01",
    chapter: "سلوك العامل",
    number: 1,
    description: "التشاجر مع الزملاء، أو مع الغير، أو إحداث مشاغبات في مكان العمل",
    penalties: { first: "FINE_1DAY", second: "FINE_2DAYS", third: "FINE_3DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-02",
    chapter: "سلوك العامل",
    number: 2,
    description: "التمارض، أو ادعاء العامل كذباً أنه أصيب أثناء العمل، أو بسببه",
    penalties: { first: "FINE_1DAY", second: "FINE_2DAYS", third: "FINE_3DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-03",
    chapter: "سلوك العامل",
    number: 3,
    description: "الامتناع عن إجراء الكشف الطبي عند طلب طبيب المنشأة، أو رفض اتباع التعليمات الطبية أثناء العلاج",
    penalties: { first: "FINE_1DAY", second: "FINE_2DAYS", third: "FINE_3DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-04",
    chapter: "سلوك العامل",
    number: 4,
    description: "مخالفة التعليمات الصحية المعلقة بأماكن العمل",
    penalties: { first: "FINE_50", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-05",
    chapter: "سلوك العامل",
    number: 5,
    description: "الكتابة على جدران المنشأة، أو لصق إعلانات عليها",
    penalties: { first: "WARNING", second: "FINE_10", third: "FINE_25", fourth: "FINE_50" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-06",
    chapter: "سلوك العامل",
    number: 6,
    description: "رفض التفتيش الإداري عند الانصراف",
    penalties: { first: "FINE_25", second: "FINE_50", third: "FINE_1DAY", fourth: "FINE_2DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-07",
    chapter: "سلوك العامل",
    number: 7,
    description: "عدم تسليم النقود المحصلة لحساب المنشأة في المواعيد المحددة دون تبرير مقبول",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-08",
    chapter: "سلوك العامل",
    number: 8,
    description: "الامتناع عن ارتداء الملابس والأجهزة المقررة للوقاية والسلامة",
    penalties: { first: "WARNING", second: "FINE_1DAY", third: "FINE_2DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-09",
    chapter: "سلوك العامل",
    number: 9,
    description: "تعمد الخلوة مع الجنس الآخر في أماكن العمل",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-10",
    chapter: "سلوك العامل",
    number: 10,
    description: "الإيحاء للآخرين بما يخدش الحياء قولاً أو فعلاً",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-11",
    chapter: "سلوك العامل",
    number: 11,
    description: "الاعتداء على زملاء العمل بالقول، أو الإشارة، أو باستعمال وسائل الاتصال الالكترونية بالشتم أو التحقير",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-12",
    chapter: "سلوك العامل",
    number: 12,
    description: "الاعتداء بالإيذاء الجسدي على زملاء العمل، أو على غيرهم بطريقة إباحية",
    penalties: { first: "TERMINATION_WITHOUT", second: null, third: null, fourth: null },
    notes: "فصل بدون مكافأة أو إشعار أو تعويض بموجب المادة (80)",
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-13",
    chapter: "سلوك العامل",
    number: 13,
    description: "الاعتداء الجسدي أو القولي أو بأي وسيلة من وسائل الاتصال الالكترونية على صاحب العمل، أو المدير المسئول، أو أحد الرؤساء أثناء العمل، أو بسببه",
    penalties: { first: "TERMINATION_WITHOUT", second: null, third: null, fourth: null },
    notes: "فصل بدون مكافأة أو إشعار أو تعويض بموجب المادة (80)",
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-14",
    chapter: "سلوك العامل",
    number: 14,
    description: "تقديم بلاغ أو شكوى كيدية",
    penalties: { first: "FINE_3DAYS", second: "FINE_5DAYS", third: "TERMINATION_WITH", fourth: null },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-15",
    chapter: "سلوك العامل",
    number: 15,
    description: "عدم الامتثال لطلب لجنة التحقيق بالحضور",
    penalties: { first: "FINE_2DAYS", second: "FINE_3DAYS", third: "FINE_5DAYS", fourth: "TERMINATION_WITH" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
  {
    id: "BH-16",
    chapter: "سلوك العامل",
    number: 16,
    description: "عدم التقييد بالزي الرسمي المعتمد بالمنشأة",
    penalties: { first: "FINE_1DAY", second: "FINE_2DAYS", third: "FINE_3DAYS", fourth: "FINE_5DAYS" },
    autoDetectable: false,
    enabled: true,
    autoApply: false,
  },
];

/* ═══ القائمة الموحدة ═══ */
export const ALL_VIOLATIONS_DEFAULT = [
  ...VIOLATIONS_WORKING_HOURS,
  ...VIOLATIONS_WORK_ORGANIZATION,
  ...VIOLATIONS_BEHAVIOR,
];

/* ═══ قواعد المادة 47 - إبلاغ الموظف قبل الجزاء ═══ */
export const PROCEDURE_RULES = {
  maxPenaltyWithoutNotice: "FINE_1DAY", // لا يوقع جزاء يتجاوز أجر يوم إلا بعد إبلاغ العامل كتابة
  responseTimeHours: 24,  // الرد خلال 24 ساعة
  investigationDays: 5,   // 5 أيام عمل لتشكيل لجنة التحقيق
  maxComplaintDays: 30,   // لا تجوز المساءلة بعد 30 يوم من علم المنشأة
  appealDays: 3,           // التظلم خلال 3 أيام عمل
  appealResponseDays: 5,   // الرد على التظلم خلال 5 أيام عمل
  repeatingThreshold: 180, // إذا مضى 180 يوم يُعد كالمرة الأولى
  maxFinePerMonth: 5,       // لا تتجاوز الغرامات أجر 5 أيام في الشهر الواحد
};

/* ═══ حالة الشكوى ═══ */
export const COMPLAINT_STATUS = {
  PENDING_HR: { code: "PENDING_HR", label: "بانتظار مراجعة HR", color: "#d4a017" },
  UNDER_INVESTIGATION: { code: "UNDER_INVESTIGATION", label: "قيد التحقيق", color: "#2b5ea7" },
  WAITING_RESPONSE: { code: "WAITING_RESPONSE", label: "بانتظار رد الموظف", color: "#8B5CF6" },
  RESPONSE_RECEIVED: { code: "RESPONSE_RECEIVED", label: "تم استلام الرد", color: "#3a7bd5" },
  CONVERTED: { code: "CONVERTED", label: "تحولت لمخالفة", color: "#E2192C" },
  REJECTED: { code: "REJECTED", label: "مرفوضة", color: "#64748b" },
  CLOSED: { code: "CLOSED", label: "مغلقة (برئ)", color: "#10b981" },
  APPEALED: { code: "APPEALED", label: "متظلم عليها", color: "#F97316" },
};

/* ═══ حالة المخالفة ═══ */
export const VIOLATION_STATUS = {
  PENDING_APPROVAL: { code: "PENDING_APPROVAL", label: "بانتظار اعتماد HR", color: "#d4a017" },
  ACTIVE: { code: "ACTIVE", label: "سارية", color: "#E2192C" },
  APPEALED: { code: "APPEALED", label: "متظلم عليها", color: "#F97316" },
  CANCELLED: { code: "CANCELLED", label: "ملغاة", color: "#64748b" },
  EXPIRED: { code: "EXPIRED", label: "منتهية (180 يوم)", color: "#94a3b8" },
};
